version: '3.8'

services:
  mysql_db:
    image: mysql
    container_name: 'mysql-cloudservice'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'cloudservice'
    volumes:
      - ./dbdata:/var/lib/mysql/

  cloud_service:
    image: 'netology-diplom-backend:latest'
    container_name: 'netology-diplom-backend'
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - mysql_db

