

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/cloudservice
    username: root
    password: mysql

jwt:
  sessionTime: 120000000
  secret: secret_key
