

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://localhost:3306/cloudservice
    username: root
    password: mysql
data:
  file_storage:
    path: target\\file_storage


jwt:
  sessionTime: 120000000
  secret: secret_key
